### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Timur5050**

### CODE REVIEW

**Review by pavlopro — CHANGES_REQUESTED** [review]
Attach screenshots according to task requirements

**Comment by Timur5050** [comment]
image
image
image
image

**Review by pavlopro — CHANGES_REQUESTED** [review]
Just found that you modified migration file
You shouldn't do this

**Comment by Timur5050** [comment]
i modified only for flake8 rules, i have just changed ' for "

**Review by pavlopro — APPROVED** [review]
Yes, I understand you
In future those type of files you should add to excluded flake8 files and not modify them

**Comment by Timur5050** [comment]
okay, i got it. so, what do i need to do now?

**Pull request closed without merging**
